# Generated by Django 2.2.4 on 2023-12-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_auto_20231217_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
